import './globals.css';
import { ReactNode } from 'react';

export const metadata = {
  title: 'Checkers Online',
  description: 'Generated by YmirJS',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="h-screen grid bg-gradient-to-b from-emerald-400 to-emerald-700">{children}</body>
    </html>
  );
}
